name: vas_ods
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  talker_flutter: ^4.7.2
  talker_dio_logger: ^4.7.2

  provider: ^6.1.2

  go_router:
    path: ./go_router

  flutter_svg: ^2.0.9

  flutter_bloc: ^8.1.4
  equatable: ^2.0.0
  built_value: ^8.8.1
  built_collection: ^5.1.1

  shared_preferences: ^2.2.2

  dio: ^5.4.1

  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1

  get_it: ^7.6.7
  injectable: ^2.3.2
  intl: ^0.19.0

  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.2

  bot_toast: ^4.0.3
  lottie: ^3.1.2
  dotted_decoration: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.13
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  intl_utils: ^2.8.7
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  built_value_generator: ^8.4.3
  flutter_launcher_icons: ^0.13.1

  modal_bottom_sheet: ^3.0.0
  google_fonts: ^6.2.1

flutter_native_splash:
  image: "assets/images/ic_logo_white.png"
  color: "#262626"
  icon_background_color: "#262626"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

flutter_intl:
  enabled: true
  class_name: Locales

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

dependency_overrides:
  web: ^1.1.0
